"use client";

import { useState } from "react";
import { BadgeCheck, CircleAlert } from "lucide-react";
import { JsonMap } from "@/lib/outputs";
import { formatNumber, percent } from "@/lib/utils";
import { Card } from "@/components/ui/card";
import { LightCurveOnDemand } from "@/components/lightcurve-on-demand";

type Candidate = JsonMap & { toi: number; benchmark_class: string; planet_like_benchmark_score: number; published_measurements: JsonMap; actual_catalogue_disposition: string; nasa_toi_row: JsonMap };

function Metric({ label, value, unit }: { label: string; value: string; unit?: string }) { return <div className="rounded-xl border border-line/80 bg-white/[.025] p-4"><p className="text-[11px] uppercase tracking-[.13em] text-slate-500">{label}</p><p className="mt-1 text-xl font-semibold text-white">{value} {unit && <span className="text-xs font-normal text-mist">{unit}</span>}</p></div>; }
function dispositionLabel(value: string) {
  return value === "CP" ? "CP — Confirmed planet" : value === "KP" ? "KP — Known planet" : value === "FP" ? "FP — False positive" : value === "FA" ? "FA — False alarm" : value || "Not listed";
}

export function CatalogueAssessment({ assessment }: { assessment: JsonMap }) {
  const candidates = (assessment.candidates as Candidate[]) || []; const [index, setIndex] = useState(0); const candidate = candidates[index];
  if (!candidate) return null;
  const thresholds = assessment.strong_classification_thresholds as JsonMap;
  const classification = candidate.benchmark_class;
  const positive = classification === "STRONGLY_PLANET_LIKE";
  const uncertain = classification === "UNCERTAIN";
  const title = positive ? "Strongly planet-like" : uncertain ? "Uncertain" : "Strongly FP / EB-like";
  const explanation = positive ? "Its benchmark-similarity score is in the validation-derived strong planet-like region." : uncertain ? "Its benchmark-similarity score falls between the two validation-derived strong regions." : "Its benchmark-similarity score is in the validation-derived strong FP / EB-like region.";
  const measures = candidate.published_measurements;
  return <main className="mx-auto max-w-6xl px-5 pb-20 pt-12 lg:px-8"><section className="border-b border-line/70 pb-8"><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">NASA TOI catalogue assessment</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">TIC {String(assessment.tic_id)}</h1><p className="mt-4 max-w-3xl leading-7 text-mist">This assessment uses numerical measurements already published in the NASA Exoplanet Archive TOI table. It does not retrieve a TESS light curve or independently discover a transit.</p>{candidates.length > 1 && <select value={index} onChange={(event) => setIndex(Number(event.target.value))} className="mt-5 rounded-lg border border-line bg-panel px-3 py-2 text-sm text-white">{candidates.map((item, itemIndex) => <option value={itemIndex} key={String(item.toi)}>TOI {formatNumber(item.toi, 2)}</option>)}</select>}</section>
    <section className="mt-8 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card className="p-7"><div className="flex items-start gap-4"><span className={`grid size-11 place-items-center rounded-xl ${positive ? "bg-emerald-300/10 text-emerald-300" : uncertain ? "bg-cyan/10 text-cyan" : "bg-amber-300/10 text-amber-200"}`}><BadgeCheck size={23} /></span><div><p className="text-xs uppercase tracking-[.14em] text-slate-500">Benchmark classification</p><h2 className="mt-2 text-2xl font-semibold text-white">{title}</h2><p className="mt-3 max-w-2xl leading-7 text-mist">{explanation} The selected model estimates similarity to the CP/KP side of the final catalogue benchmark; it is not a physical confirmation probability.</p></div></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><Metric label="Benchmark-similarity score" value={percent(candidate.planet_like_benchmark_score, 1)} /><Metric label="Strong FP / EB through" value={percent(thresholds.strong_fp_eb_max_score, 1)} /><Metric label="Strong planet-like from" value={percent(thresholds.strong_planet_like_min_score, 1)} /><Metric label="Published TOI" value={formatNumber(candidate.toi, 2)} /></div></Card><Card className="p-6"><CircleAlert className="text-cyan" size={21} /><p className="mt-5 text-xs uppercase tracking-[.14em] text-slate-500">NASA catalogue disposition</p><h2 className="mt-2 text-xl font-semibold text-white">{dispositionLabel(candidate.actual_catalogue_disposition)}</h2><p className="mt-3 text-sm leading-7 text-mist">NASA&apos;s published label is shown after ExoSignal&apos;s result for comparison. It was never supplied to the model as an input.</p><div className="mt-5 border-t border-line pt-4"><h3 className="text-sm font-medium text-white">About ExoSignal&apos;s result</h3><p className="mt-2 text-sm leading-7 text-mist">Strong regions use validation TICs only and require at least {percent(thresholds.minimum_observed_validation_purity, 0)} observed class agreement. This is still not a physical confirmation probability.</p></div></Card></section>
    <section className="mt-12"><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">Published numerical measurements</p><h2 className="mt-2 text-2xl font-semibold">Inputs supplied to the model</h2><p className="mt-2 max-w-3xl leading-7 text-mist">NASA&apos;s original numerical column names are retained. Identity, names, disposition, dates, and catalogue-status fields are excluded from the model.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="pl_orbper" value={formatNumber(measures.pl_orbper, 5)} unit="days" /><Metric label="pl_trandurh" value={formatNumber(measures.pl_trandurh, 3)} unit="hours" /><Metric label="pl_trandep" value={formatNumber(measures.pl_trandep, 1)} unit="ppm" /><Metric label="st_tmag" value={formatNumber(measures.st_tmag, 3)} /><Metric label="st_dist" value={formatNumber(measures.st_dist, 1)} unit="pc" /><Metric label="st_teff" value={formatNumber(measures.st_teff, 0)} unit="K" /><Metric label="st_logg" value={formatNumber(measures.st_logg, 3)} /><Metric label="st_rad" value={formatNumber(measures.st_rad, 3)} unit="R☉" /></div></section>
    <section className="mt-12 grid gap-5 lg:grid-cols-2"><Card className="p-6"><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">Catalogue reveal</p><h2 className="mt-2 text-xl font-semibold">NASA&apos;s published disposition</h2><p className="mt-3 text-2xl font-semibold text-white">{candidate.actual_catalogue_disposition || "Not listed"}</p><p className="mt-3 text-sm leading-6 text-mist">Shown after the model result for comparison only; it was never supplied to the model.</p></Card><Card className="p-6"><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">On-demand photometry</p><h2 className="mt-2 text-xl font-semibold">Retrieve the TESS light curve</h2><p className="mt-3 text-sm leading-6 text-mist">This is separate from catalogue classification. It downloads and processes public SPOC light curves only for this TIC when requested.</p><div className="mt-5"><LightCurveOnDemand ticId={String(assessment.tic_id)} /></div></Card></section>
    <section className="mt-12"><details className="rounded-xl border border-line bg-panel p-5"><summary className="cursor-pointer font-medium text-white">More info: full NASA TOI catalogue row</summary><p className="mt-3 text-sm leading-6 text-mist">This public row is shown for provenance. Catalogue fields, including the disposition, are not model inputs.</p><dl className="mt-5 grid gap-x-8 gap-y-3 sm:grid-cols-2">{Object.entries(candidate.nasa_toi_row || {}).map(([name, value]) => <div key={name} className="border-t border-line/70 pt-2"><dt className="font-mono text-xs text-slate-500">{name}</dt><dd className="mt-1 break-words text-sm text-mist">{value === null ? "—" : String(value)}</dd></div>)}</dl></details></section>
  </main>;
}
