"use client";

import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, CircleAlert, Eye, MapPin, Orbit, Telescope } from "lucide-react";
import { Event, JsonMap, TargetData } from "@/lib/outputs";
import { artifactUrl } from "@/lib/artifacts";
import { formatNumber, percent } from "@/lib/utils";
import { Card } from "@/components/ui/card";
import { StatusBadge } from "@/components/ui/badge";

function value(map: JsonMap | undefined, key: string) { return map?.[key] as JsonMap | undefined; }
function scalar(map: JsonMap | undefined, key: string) { const item = map?.[key]; return typeof item === "number" || typeof item === "string" ? item : undefined; }
function title(name: string) { return name.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }

function Metric({ label, value: metric, unit }: { label: string; value: string; unit?: string }) { return <div className="rounded-xl border border-line/80 bg-white/[.025] px-4 py-3"><p className="text-[11px] font-medium uppercase tracking-[.13em] text-slate-500">{label}</p><p className="mt-1 text-xl font-semibold tracking-tight text-white">{metric}<span className="ml-1 text-xs font-normal text-mist">{unit}</span></p></div>; }

function Plot({ src, title, caption, large = false }: { src: string; title: string; caption: string; large?: boolean }) { return <Card className={large ? "p-4 lg:col-span-2" : "p-4"}><div className="mb-3 flex items-center justify-between"><h3 className="font-medium text-white">{title}</h3><span className="text-xs text-slate-500">Matplotlib output</span></div><img className="w-full rounded-lg border border-line/80 bg-[#06101d]" src={src} alt={title} /><p className="mt-3 text-sm leading-6 text-mist">{caption}</p></Card>; }

function EventViewer({ events }: { events: Event[] }) {
  const [index, setIndex] = useState(0); if (!events.length) return <Card className="p-6 text-sm text-mist">No stored event-level measurements are available for this candidate.</Card>;
  const event = events[index]; const category = event.category || "NOT AVAILABLE";
  return <Card className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.14em] text-slate-500">Individual transit</p><h3 className="mt-1 text-lg font-medium text-white">Event {event.event_number || index + 1} of {events.length}</h3></div><StatusBadge status={category === "detected" ? "PASS" : category === "noisy_consistent" ? "WARNING" : category === "weak_or_absent" ? "FAIL" : "NOT AVAILABLE"} /></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Predicted midtime" value={formatNumber(event.predicted_midtime_btjd, 5)} unit="BTJD" /><Metric label="Measured depth" value={percent(event.depth, 3)} /><Metric label="SNR" value={formatNumber(event.depth_snr, 2)} /></div><p className="mt-4 text-sm leading-6 text-mist">{category === "detected" ? "A measurable dip was found in adequately sampled observations." : category === "noisy_consistent" ? "The event is compatible with a dip but does not reach the detection threshold." : category === "weak_or_absent" ? "Adequate coverage exists, but the expected dip is weak or absent." : "This predicted event lacks enough usable cadence coverage for a depth measurement."}</p><div className="mt-5 flex justify-between"><button onClick={() => setIndex((current) => Math.max(0, current - 1))} disabled={!index} className="inline-flex items-center gap-1 text-sm text-cyan disabled:text-slate-600"><ChevronLeft size={16} />Previous</button><button onClick={() => setIndex((current) => Math.min(events.length - 1, current + 1))} disabled={index === events.length - 1} className="inline-flex items-center gap-1 text-sm text-cyan disabled:text-slate-600">Next<ChevronRight size={16} /></button></div></Card>;
}

function Diagnostics({ dossier }: { dossier?: JsonMap }) {
  if (!dossier) return <Card className="p-6 text-sm text-mist">No vetting dossier is available for this candidate.</Card>;
  return <div className="grid gap-3 md:grid-cols-2">{Object.entries(dossier).filter(([name]) => name !== "overall" && name !== "pixel_source_check").map(([name, raw]) => { const diagnostic = raw as JsonMap; const values = value(diagnostic, "values"); const measured = values ? Object.entries(values).filter(([, item]) => typeof item === "number").slice(0, 2) : []; return <Card key={name} className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-medium text-white">{title(name)}</h3><p className="mt-2 text-sm leading-6 text-mist">{String(scalar(diagnostic, "explanation") || "No explanation supplied.")}</p></div><StatusBadge status={String(scalar(diagnostic, "status") || "NOT AVAILABLE")} /></div>{measured.length > 0 && <div className="mt-4 flex flex-wrap gap-2">{measured.map(([key, measurement]) => <span key={key} className="rounded-md bg-white/[.05] px-2.5 py-1.5 text-xs text-slate-300">{title(key)} <strong className="ml-1 text-white">{formatNumber(measurement, 4)}</strong></span>)}</div>}<details className="mt-4 text-sm"><summary className="cursor-pointer text-cyan">Criterion</summary><p className="mt-2 leading-6 text-slate-400">{String(scalar(diagnostic, "criterion") || "—")}</p></details></Card>; })}</div>;
}

function PixelSection({ dossier, assetBase, candidateId }: { dossier?: JsonMap; assetBase: string; candidateId: string }) {
  const pixel = value(dossier, "pixel_source_check"); const values = value(pixel, "values"); const results = Array.isArray(values?.sector_results) ? values.sector_results as JsonMap[] : [];
  if (!pixel || !results.length) return <Card className="p-6"><div className="flex gap-3"><CircleAlert className="mt-1 text-slate-400" /><div><h3 className="font-medium text-white">Source location not available</h3><p className="mt-2 text-sm leading-6 text-mist">No suitable target-pixel diagnostic was persisted. This is an absence of localisation evidence, not a conclusion about the candidate.</p></div></div></Card>;
  return <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Card className="p-4"><img className="w-full rounded-lg border border-line bg-[#06101d]" src={artifactUrl(`${assetBase}/candidates/${candidateId.toLowerCase()}_pixel_diagnostic.png`)} alt="Pixel source-location diagnostic" /><p className="mt-3 text-sm leading-6 text-mist">Out-of-transit, in-transit, and difference-image views show where the flux loss is localised. Target and inferred flux-loss positions are overlaid.</p></Card><Card className="p-5"><div className="flex items-center justify-between"><h3 className="font-medium text-white">Sector-level offsets</h3><StatusBadge status={String(scalar(pixel, "status") || "NOT AVAILABLE")} /></div><p className="mt-2 text-sm leading-6 text-mist">{String(scalar(pixel, "explanation") || "")}</p><div className="mt-4 space-y-2">{results.slice(0, 6).map((result) => <div key={String(result.sector)} className="flex items-center justify-between rounded-lg border border-line/70 px-3 py-2"><span className="text-sm text-slate-200">Sector {String(result.sector)}</span><span className="text-sm text-mist">{formatNumber(result.offset_pixels, 3)} px · {String(result.interpretation)}</span></div>)}</div></Card></div>;
}

export function TargetReport({ target }: { target: TargetData }) {
  const [candidateId, setCandidateId] = useState(target.candidates[0]?.candidate_id || "");
  const candidate = useMemo(() => target.candidates.find((item) => item.candidate_id === candidateId) || target.candidates[0], [candidateId, target.candidates]);
  if (!candidate) return null;
  const dossier = target.dossiers[candidate.candidate_id]; const overall = value(dossier, "overall"); const sectors = Array.isArray(target.metadata.sectors_available) ? target.metadata.sectors_available : [];
  const assetBase = target.root;
  return <main className="mx-auto max-w-7xl px-5 pb-20 pt-10 lg:px-8"><section className="border-b border-line/70 pb-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">Candidate dossier</p><h1 className="mt-2 text-4xl font-semibold tracking-tight text-white">TIC {target.ticId} <span className="text-mist">/ {candidate.candidate_id}</span></h1><p className="mt-3 text-sm text-mist">{sectors.length} observed sectors · {target.candidates.length} detected candidates · locally persisted analysis</p></div><div className="min-w-48"><label className="text-xs uppercase tracking-[.12em] text-slate-500">Candidate</label><select value={candidateId} onChange={(event) => setCandidateId(event.target.value)} className="mt-2 w-full rounded-lg border border-line bg-panel px-3 py-2 text-sm text-white">{target.candidates.map((item) => <option key={item.candidate_id}>{item.candidate_id} · {formatNumber(item.period_days, 4)} d</option>)}</select></div></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-7"><Metric label="Period" value={formatNumber(candidate.period_days, 6)} unit="days" /><Metric label="Transit depth" value={percent(candidate.depth, 3)} /><Metric label="Duration" value={formatNumber(candidate.duration_hours, 2)} unit="h" /><Metric label="Observed transits" value={formatNumber(candidate.observed_transits, 0)} /><Metric label="BLS SNR" value={formatNumber(candidate.bls_snr, 1)} /><Metric label="ML ranking" value={formatNumber(candidate.ranking_score, 3)} /><div className="rounded-xl border border-line/80 bg-white/[.025] px-4 py-3"><p className="text-[11px] font-medium uppercase tracking-[.13em] text-slate-500">Vetting result</p><div className="mt-2"><StatusBadge status={String(scalar(overall, "status") || "NOT AVAILABLE")} /></div></div></div></section>
    <div className="mt-8 grid gap-8 lg:grid-cols-[13rem_1fr]"><aside className="hidden lg:block"><nav className="sticky top-24 space-y-1 text-sm"><p className="mb-3 text-xs uppercase tracking-[.14em] text-slate-500">Report sections</p>{[["Overview", "overview"], ["Transit signal", "signal"], ["Transit events", "events"], ["Vetting", "vetting"], ["Pixel inspection", "pixel"]].map(([label, id]) => <a key={id} href={`#${id}`} className="block rounded-md px-3 py-2 text-mist hover:bg-white/[.04] hover:text-white">{label}</a>)}</nav></aside><div className="space-y-12"><section id="overview"><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">Overview</p><div className="mt-4 grid gap-5 lg:grid-cols-2"><Card className="p-6"><h2 className="text-xl font-semibold text-white">Candidate interpretation</h2><p className="mt-3 leading-7 text-mist">This signal is ranked for follow-up using measured transit and vetting evidence. A ranking score is not a confirmation probability and cannot establish a planet without further analysis.</p><div className="mt-5 grid grid-cols-2 gap-3"><Metric label="ML ranking score" value={formatNumber(candidate.ranking_score, 3)} /><Metric label="TESS magnitude" value={formatNumber(target.metadata.tmag, 2)} /><Metric label="Stellar radius" value={formatNumber(target.metadata.stellar_radius_rsun, 3)} unit="R☉" /><Metric label="Temperature" value={formatNumber(target.metadata.teff_k, 0)} unit="K" /><Metric label="Crowding" value={formatNumber(target.metadata.crowdsap, 3)} /></div></Card><Card className="p-6"><div className="flex items-center gap-2 text-cyan"><Telescope size={18} /><h2 className="text-xl font-semibold text-white">Observing context</h2></div><div className="mt-5 space-y-3">{(Array.isArray(target.sectors.processed_sectors) ? target.sectors.processed_sectors as JsonMap[] : []).map((sector) => <div key={String(sector.sector)} className="flex items-center justify-between rounded-lg border border-line/70 px-3 py-3"><span className="text-sm text-white">Sector {String(sector.sector)}</span><span className="text-xs text-mist">{formatNumber(sector.output_cadences, 0)} usable cadences</span></div>)}</div></Card></div></section>
      <section id="signal"><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">Transit signal</p><h2 className="mt-2 text-2xl font-semibold text-white">Signal evidence</h2><p className="mt-2 max-w-3xl leading-7 text-mist">The phase-folded view is primary evidence for the periodic dip. The full light curve and BLS periodogram retain the context needed to assess systematics and aliases.</p><div className="mt-5 grid gap-5 lg:grid-cols-2"><Plot large src={artifactUrl(`${assetBase}/candidates/${candidate.candidate_id.toLowerCase()}_phase_folded.png`)} title="Phase-folded transit" caption="Cadences folded at the candidate period. The expected transit window is centred at phase zero." /><Plot src={artifactUrl(`${assetBase}/processed_lightcurve.png`)} title="Processed TESS light curve" caption="Sector-aware, detrended PDCSAP relative flux used by the transit search." /><Plot src={artifactUrl(`${assetBase}/candidates/${candidate.candidate_id.toLowerCase()}_bls_periodogram.png`)} title="BLS periodogram" caption="Search power across tested orbital periods; peaks require astrophysical scrutiny." /></div></section>
      <section id="events"><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">Transit events</p><h2 className="mt-2 text-2xl font-semibold text-white">One event at a time</h2><p className="mt-2 mb-5 leading-7 text-mist">Individual predicted events remain distinct from observational gaps and insufficient cadence coverage.</p><EventViewer events={target.events[candidate.candidate_id] || []} /></section>
      <section id="vetting"><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">Astrophysical vetting</p><h2 className="mt-2 mb-5 text-2xl font-semibold text-white">Measured checks, not verdict theatre</h2><Diagnostics dossier={dossier} /></section>
      <section id="pixel"><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">Pixel / source location</p><h2 className="mt-2 mb-5 text-2xl font-semibold text-white">Where is the flux loss?</h2><PixelSection dossier={dossier} assetBase={assetBase} candidateId={candidate.candidate_id} /></section>
    </div></div></main>;
}
