import { BarChart3, CheckCircle2, FlaskConical, Scale } from "lucide-react";
import { getValidation } from "@/lib/outputs";
import { artifactUrl } from "@/lib/artifacts";
import { formatNumber } from "@/lib/utils";
import { Card } from "@/components/ui/card";

function Score({ label, value }: { label: string; value: unknown }) { return <div className="rounded-lg border border-line/70 bg-white/[.025] px-3 py-3"><p className="text-[10px] uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-1 font-mono text-lg text-white">{formatNumber(value, 3)}</p></div>; }

export default async function ValidationPage() {
  const { report, benchmark, injection } = await getValidation(); const logistic = report.logistic_regression_test as Record<string, unknown>; const forest = report.calibrated_random_forest_test as Record<string, unknown>; const detection = benchmark.detection_performance as Record<string, unknown>; const attrition = benchmark.attrition as Record<string, unknown>;
  const exact = injection.filter((row) => row.recovery === "exact_period").length; const harmonic = injection.filter((row) => row.recovery === "simple_harmonic").length;
  return <main className="mx-auto max-w-7xl px-5 pb-20 pt-12 lg:px-8"><section className="max-w-4xl"><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">Validation evidence</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">How well does ExoSignal hold up?</h1><p className="mt-4 text-lg leading-8 text-mist">Validation is presented as evidence with constraints—not a single headline number. Detection recovery, candidate ranking, and injection sensitivity are separate questions.</p></section>
    <section className="mt-10 grid gap-4 md:grid-cols-4">{[["Labelled TICs", benchmark.source_labelled_tics], ["Recovered signals", detection.recovered_known_signals], ["Exact period", detection.exact_recoveries], ["Known non-recoveries", detection.known_signal_not_recovered]].map(([label, value]) => <Card key={String(label)} className="p-5"><p className="text-xs uppercase tracking-[.13em] text-slate-500">{String(label)}</p><p className="mt-2 text-3xl font-semibold">{String(value)}</p></Card>)}</section>
    <section className="mt-14 grid gap-7 lg:grid-cols-[.8fr_1.2fr]"><div><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">Held-out model comparison</p><h2 className="mt-2 text-2xl font-semibold">Logistic Regression selected</h2><p className="mt-3 leading-7 text-mist">The selected Logistic Regression model had stronger held-out PR-AUC and ROC-AUC, a lower Brier score, and higher precision while retaining the same recall as the calibrated Random Forest.</p><div className="mt-5 rounded-xl border border-cyan/20 bg-cyan/5 p-4 text-sm text-cyan">Calibration used validation TICs only: 10 negative and 11 positive targets. The final test partition remained untouched until evaluation.</div></div><div className="grid gap-4 sm:grid-cols-2">{[["Logistic Regression", logistic], ["Calibrated Random Forest", forest]].map(([name, metrics]) => <Card key={String(name)} className="p-5"><h3 className="font-medium text-white">{String(name)}</h3><div className="mt-4 grid grid-cols-2 gap-3">{["precision", "recall", "pr_auc", "roc_auc", "brier_score"].map((key) => <Score key={key} label={key.replace("_", " ")} value={(metrics as Record<string, unknown>)[key]} />)}</div></Card>)}</div></section>
    <section className="mt-10"><Card className="p-4"><img className="w-full rounded-lg border border-line" src={artifactUrl("models/held_out_model_evaluation.png")} alt="Held-out confusion matrix and calibration curves" /><p className="px-2 pt-3 text-sm leading-6 text-mist">Held-out confusion matrix and calibration curves. Small test populations make these descriptive evidence rather than final performance guarantees.</p></Card></section>
    <section className="mt-14 grid gap-7 lg:grid-cols-2"><div><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">Injection / recovery</p><h2 className="mt-2 text-2xl font-semibold">Real TESS noise, controlled signal</h2><p className="mt-3 leading-7 text-mist">A 4×4 period × depth grid was injected before long-timescale detrending on one real target, then searched through the normal BLS path.</p><div className="mt-5 grid grid-cols-3 gap-3"><Score label="Trials" value={injection.length} /><Score label="Exact" value={exact} /><Score label="Harmonic" value={harmonic} /></div><p className="mt-5 text-sm leading-6 text-slate-400">The persistent competing ≈1.398-day signal in this target makes this a workflow sensitivity study, not a global completeness estimate.</p></div><Card className="p-4"><img className="w-full rounded-lg border border-line" src={artifactUrl("targets/98796344/injection_recovery.png")} alt="Injection recovery sensitivity map" /></Card></section>
    <section className="mt-14"><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">Limitations</p><div className="mt-4 grid gap-4 md:grid-cols-3">{[[BarChart3, "Modest benchmark", "The labelled benchmark and especially the held-out partition remain small."], [FlaskConical, "One-target injection", "Injection sensitivity is measured on one real TESS noise environment."], [Scale, "Workflow demonstration", "The three-TIC blind discovery run validates ordering and persistence, not discovery yield."]].map(([Icon, title, text]) => <Card key={String(title)} className="p-5"><Icon className="text-violet" size={20} /><h3 className="mt-5 font-medium">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-mist">{String(text)}</p></Card>)}</div></section>
  </main>;
}
