import Link from "next/link";
import { ArrowRight, Database, ShieldCheck, Telescope } from "lucide-react";
import { getValidation } from "@/lib/outputs";
import { percent } from "@/lib/utils";
import { Card } from "@/components/ui/card";

export default async function SummaryPage() {
  const { benchmark, report } = await getValidation();
  const selected = String(report.selected_ranking_model || "calibrated_random_forest");
  const metrics = report[`${selected}_test`] as Record<string, unknown>;
  return <main className="mx-auto max-w-7xl px-5 pb-20 pt-16 lg:px-8 lg:pt-24"><section className="grid gap-12 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><p className="mb-5 font-mono text-xs font-medium uppercase tracking-[.22em] text-cyan">Catalogue benchmark complete</p><h1 className="max-w-3xl text-5xl font-semibold leading-[1.02] tracking-[-.045em] text-white sm:text-6xl">{String(benchmark.targets)} NASA TOI candidates, assessed transparently.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-mist">ExoSignal&apos;s final catalogue classifier has completed its train, validation, and held-out test workflow. Browse every analysed TIC, compare its result with NASA&apos;s published disposition, and retrieve a TESS light curve only when you choose to inspect that object.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/catalogue" className="inline-flex items-center gap-2 rounded-lg bg-cyan px-4 py-2.5 text-sm font-medium text-slate-950 transition hover:bg-cyan/85">Browse all analysed TICs <ArrowRight size={16} /></Link></div></div><Card className="relative overflow-hidden p-7"><p className="text-sm font-medium text-mist">Benchmark accuracy</p><p className="mt-3 text-5xl font-semibold tracking-tight text-white">{percent(metrics.accuracy, 1)}</p><p className="mt-1 text-sm text-mist">Agreement with published NASA catalogue dispositions.</p><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-lg border border-line bg-white/[.025] p-3"><p className="text-[10px] uppercase tracking-[.12em] text-slate-500">PR-AUC</p><p className="mt-1 font-mono text-lg">{percent(metrics.pr_auc, 1)}</p></div><div className="rounded-lg border border-line bg-white/[.025] p-3"><p className="text-[10px] uppercase tracking-[.12em] text-slate-500">ROC-AUC</p><p className="mt-1 font-mono text-lg">{percent(metrics.roc_auc, 1)}</p></div></div></Card></section><section className="mt-20 grid gap-4 md:grid-cols-3">{[[Database, "Catalogue scale", `${String(benchmark.positive_targets)} CP/KP and ${String(benchmark.negative_targets)} FP/FA TICs; no light curves used for training.`], [ShieldCheck, "Independent check", "Results are compared with NASA catalogue labels that were not provided to the model as answers."], [Telescope, "Light curves on demand", "Open any TIC in the catalogue to retrieve public TESS photometry only for that individual target."]].map(([Icon, title, text]) => <Card key={String(title)} className="p-6"><Icon className="text-cyan" size={21} /><h2 className="mt-5 text-lg font-semibold">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-mist">{String(text)}</p></Card>)}</section></main>;
}
