import { LockKeyhole, SearchCheck } from "lucide-react";
import { getDiscovery } from "@/lib/outputs";
import { Card } from "@/components/ui/card";
import { DiscoveryTable } from "@/components/discovery-table";

export default async function DiscoveryPage() {
  const data = await getDiscovery(); const ranking = data.ranking;
  const attempted = Number(data.parameters.targets_attempted || data.manifest.length); const successful = data.manifest.filter((row) => row.status === "success").length; const signals = ranking.length; const highRanked = ranking.filter((row) => Number(row.planet_like_probability) >= .5).length;
  return <main className="mx-auto max-w-7xl px-5 pb-20 pt-12 lg:px-8"><section className="flex flex-col justify-between gap-7 border-b border-line/70 pb-8 md:flex-row"><div><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">Blind discovery workflow demonstration</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Discovery, with the catalogue held back.</h1><p className="mt-3 max-w-3xl leading-7 text-mist">A three-TIC demonstration of ExoSignal&apos;s full ordering: search, vet, rank, freeze, then reveal. It is evidence that the workflow runs—not a discovery-performance benchmark.</p></div><Card className="shrink-0 p-4"><div className="flex items-center gap-3"><LockKeyhole className="text-cyan" size={20} /><div><p className="text-xs uppercase tracking-[.12em] text-slate-500">Frozen ranking SHA-256</p><p className="mt-1 max-w-56 break-all font-mono text-xs text-slate-200">{String(data.parameters.pre_crossmatch_ranking_sha256 || "—")}</p></div></div></Card></section>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Targets analysed", `${successful} / ${attempted}`], ["Signals ranked", String(signals)], ["High-ranked", String(highRanked)], ["TOI period matches", "0"], ["Queried-TOI non-matches", String(signals)]].map(([label, value]) => <Card key={label} className="p-5"><p className="text-xs uppercase tracking-[.13em] text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold text-white">{value}</p></Card>)}</section>
    <section className="mt-12"><div className="flex items-end justify-between"><div><p className="font-mono text-xs uppercase tracking-[.18em] text-cyan">Candidate catalogue</p><h2 className="mt-2 text-2xl font-semibold">Pre-crossmatch ExoSignal ranking</h2></div><span className="text-sm text-mist">Candidate ranking is not confirmation</span></div><Card className="mt-5 overflow-hidden p-3"><DiscoveryTable ranking={ranking} reveal={data.reveal} /></Card><p className="mt-4 flex max-w-4xl gap-2 text-sm leading-6 text-mist"><SearchCheck className="mt-1 shrink-0 text-cyan" size={16} />A queried-TOI non-match is not a planet discovery or a global catalogue non-match. Further catalogue and human follow-up are required.</p></section>
  </main>;
}
